import { NewsArticle } from './types';

export const mockArticles: NewsArticle[] = [
  {
    id: '1',
    title: 'MihirSync Unveils Next-Gen AI News Engine for Global Audiences',
    slug: 'mihirsync-unveils-next-gen-ai-news-engine',
    content: 'Full content here...',
    excerpt: 'The revolutionary platform combines real-time data processing with advanced natural language generation to provide unbiased, lightning-fast news coverage across 12 categories.',
    author: 'Mihir Atodariya',
    category: 'Technology',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200',
    publishedAt: new Date().toISOString(),
    isTrending: true,
    isBreaking: true,
    views: 125400,
    readTime: '5 min read',
    tags: ['AI', 'Tech', 'Launch']
  },
  {
    id: '2',
    title: 'World Economies Pivot Towards Standardized Digital Currency Frameworks',
    slug: 'world-economies-pivot-standardized-digital-currency',
    content: 'Full content here...',
    excerpt: 'Major central banks announced a collaborative effort to stabilize digital asset markets and integrate blockchain technology into sovereign financial systems.',
    author: 'Sarah Johnson',
    category: 'Finance',
    image: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?auto=format&fit=crop&q=80&w=1200',
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    isTrending: true,
    isBreaking: false,
    views: 89000,
    readTime: '4 min read',
    tags: ['Crypto', 'Economy', 'Global']
  },
  {
    id: '3',
    title: 'Climate Tech Startups Secure Record-Breaking $40B in Q1 Funding',
    slug: 'climate-tech-startups-secure-record-funding',
    content: 'Full content here...',
    excerpt: 'Investors are doubling down on carbon capture and renewable energy storage solutions as global climate goals become more urgent.',
    author: 'David Chen',
    category: 'Startups',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1200',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    isTrending: false,
    isBreaking: false,
    views: 45000,
    readTime: '3 min read',
    tags: ['Climate', 'Funding', 'VC']
  },
  {
    id: '4',
    title: 'The Rise of Generative AI in Professional Sports Analytics',
    slug: 'generative-ai-sports-analytics',
    content: 'Full content here...',
    excerpt: 'How leading teams are using machine learning to predict injury risks and optimize player performance in real-time.',
    author: 'Michael Smith',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&q=80&w=1200',
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    isTrending: true,
    isBreaking: false,
    views: 67200,
    readTime: '6 min read',
    tags: ['Sports', 'AI', 'Analytics']
  },
  {
    id: '5',
    title: 'SpaceX Successfully Tests Starship Orbital Fuel Transfer',
    slug: 'spacex-starship-fuel-transfer-test',
    content: 'Full content here...',
    excerpt: 'A critical milestone for deep space exploration was achieved today as propellant was transferred between two spacecraft in low Earth orbit.',
    author: 'Elena Rodriguez',
    category: 'Space',
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&q=80&w=1200',
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    isTrending: false,
    isBreaking: true,
    views: 112000,
    readTime: '4 min read',
    tags: ['SpaceX', 'NASA', 'Mars']
  },
  {
    id: '6',
    title: 'India Advances Digital Infrastructure with 6G Research Initiative',
    slug: 'india-advances-6g-research-initiative',
    content: 'Full content here...',
    excerpt: 'The government has greenlit a multi-billion dollar project to position India as a global leader in next-generation telecommunications.',
    author: 'Rahul Sharma',
    category: 'India',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=1200',
    publishedAt: new Date(Date.now() - 18000000).toISOString(),
    isTrending: true,
    isBreaking: false,
    views: 95000,
    readTime: '5 min read',
    tags: ['India', 'Tech', '6G']
  }
];
